### ISSUE TITLE
Doesn't work for me - F8 does nothing

### ISSUE THREAD

**Issue by Leonixar** [Str3amR/CaptainOfIndustryMods#1]
Hello there mister developer,

well my problem is very simple... I can't seem to make your "mod" work... o.o
I have it in right directory:
- C:\Users\m***k\OneDrive\Dokumenty\CaptainOfIndustry\Mods\CheatMenu\

And I have the latest version, which is Beta 0.3.3 :D This game isn't probably on the internet as warez, but still for verification I told you everything which should be important for you... O.o

Well... what do you think? :o

**Comment by Str3amR** [comment]
Hi! Please make sure to create a new game to enable the mod, COI devs recently made a change to sync the mods with the savegame so we can't load new mods with an existing save. I hope they will enhance that at some point.

**Comment by Leonixar** [comment]
Thank you for response! Well, that's a kinda shame, I don't want to create a new game right now... well... let's hope that developers will change this. I don't want to start one game every time when new interesting mod show up... :D
